title: 8-Bit Breadboard Computer
description: An 8-Bit computer built completely on breadboards
theme: just-the-docs

#url: https://just-the-docs.github.io

aux_links:
  View Project on GitHub: https://github.com/CodingFactoryT/8-Bit-Breadboard-Computer
